### ISSUE TITLE
Base table or view not found: nodes' doesn't exist 

### ISSUE THREAD

**Issue by subhasundardass** [NuclearCMS/Nuclear#5]
When I run php artisan migrate --seed, Its shows following error

**[Illuminate\Database\QueryException]**                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nuclear-cms.node  
  s' doesn't exist (SQL: select * from `nodes` where `home` = 1 and `mailing`  
   = 0 and (`status` >= 50 or (`status` >= 40 and `published_at` <= 2017-02-1  
  1 16:31:30)) limit 1)  

### [PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nuclear-cms.node  
  s' doesn't exist

**Comment by Hyleeh** [comment]
I need more info to answer that

Did you run the installation suite first?
